name: Scala CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'            # Specify Java version 21
          distribution: 'temurin'       # Specify the distribution (like 'temurin', 'zulu', etc.)

      - name: Cache SBT dependencies
        uses: actions/cache@v2
        with:
          path: ~/.sbt/boot
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
          
      - name: Run tests
        run: sbt test
